# Generated by Django 4.1 on 2022-09-14 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profilemodel'),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='jobs.tagmodel'),
        ),
        migrations.AddField(
            model_name='applicantmodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobmodel'),
        ),
        migrations.AddField(
            model_name='applicantmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='users.profilemodel'),
        ),
        migrations.AlterUniqueTogether(
            name='applicantmodel',
            unique_together={('user', 'job')},
        ),
    ]
